#!/usr/bin/php
<?php
error_reporting(E_STRICT | E_ALL);
require_once("register.php");

$reg = new register("WDOG_CTL", "Watchdog Control Register", 0xFFC00200, 0x0AD0, 16, "RW", "",
	array(
		array(15, 15, "WDRO", "0 - Watchdog timer has not expired\n1 - Watchdog timer has expired", "W1C"),
		array(11, 4, "WDEN", "0xAD - Counter disabled\nAll other values - Counter enabled"),
		array(2, 1, "WDEV", "00 - Generate reset event\n01 - Generate NMI\n10 - Generate GP interrupt\n11 - Disable event generation")
	)
);
/*
$reg = new register("WDOG_STAT", "Watchdog Status Register", 0xFFC00208, 0x0, 32, "RW", "",
	array(
		array(31, 0, "Status"),
	)
);
$reg = new register("PLL_CTL", "PLL Control Register", "0xFFC00000", 0x1400, 16, "RW", "",
	array(
		array(14, 9, "MSEL (Multiplier Select)", "See HRM for CLKIN/VCO multiplication factors"),
		array(8, 8, "BYPASS", "0 - Do not bypass PLL\n1 - BYPASS PLL"),
		array(7, 7, "Output Delay", "0 - Do not add output delay\n1 - Add approximately 200 ps of delay to external memory output signals"),
		array(6, 6, "Input Delay", "0 - Do not add input delay\n1 - Add approximately 200 ps of delay to the time when inputs are latched on the external memory interface"),
		array(5, 5, "DF (Divide Frequency)", "0 - Pass CLKIN to PLL\n1 - Pass CLKIN/2 to PLL"),
		array(3, 3, "PLL_OFF", "0 - Enable power to PLL\n1 - Disable power to PLL"),
		array(1, 1, "STOPCK (Stop Clock)", "0 - CCLK on\n1 - CCLK off"),
		array(0, 0, "PDWN (Power Down)", "0 - All internal clocks on\n1 - All internal clocks off")
	)
);
/*
$reg = new register("SEQSTAT", "Sequencer Status Register", "sysreg", 0, 32, "RO", "moo",
	array(
		array(18, 14, "HWERRCAUSE", "Holds cause of last hardware error generated by the core"),
		array(13, 13, "SFTRESET"),
		array(5, 0, "EXCAUSE"),
	)
);
/*
$reg = new register("FAR", "File Attributes Record", "undef", "undef", 5*8,
	array(
		array(6*8-1, 4*8, "REC_LEN"),
		array(4*8-1, 3*8, "REC_TYP"),
		array(3*8-1, 2*8, "REC_SUB"),
		array(2*8-1, 1*8, "CPU_TYPE"),
		array(1*8-1, 0*8, "STDF_VER")
	)
);
*/
$reg->render("register.png");
?>
